/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./src/components/NiSkeleton/src/NiSkeletonCard1 copy 2.vue')['default']
    copy: typeof import('./src/components/NiSkeleton/src/NiSkeletonVideo16_9 copy.vue')['default']
    Example: typeof import('./src/components/NiVLayout/docs/Example.vue')['default']
    IExample: typeof import('./src/components/NiVLayout/docs/IExample.vue')['default']
    NiSkeletonAvatar: typeof import('./src/components/NiSkeleton/src/NiSkeletonAvatar.vue')['default']
    NiSkeletonButtonPrimary: typeof import('./src/components/NiSkeleton/src/NiSkeletonButtonPrimary.vue')['default']
    NiSkeletonButtonSecondary: typeof import('./src/components/NiSkeleton/src/NiSkeletonButtonSecondary.vue')['default']
    NiSkeletonCard1: typeof import('./src/components/NiSkeleton/src/NiSkeletonCard1.vue')['default']
    NiSkeletonCard2: typeof import('./src/components/NiSkeleton/src/NiSkeletonCard2.vue')['default']
    NiSkeletonCard3: typeof import('./src/components/NiSkeleton/src/NiSkeletonCard3.vue')['default']
    NiSkeletonCTASection: typeof import('./src/components/NiSkeleton/src/NiSkeletonCTASection.vue')['default']
    NiSkeletonFile1_1: typeof import('./src/components/NiSkeleton/src/NiSkeletonFile1_1.vue')['default']
    NiSkeletonFile16_9: typeof import('./src/components/NiSkeleton/src/NiSkeletonFile16_9.vue')['default']
    NiSkeletonFile4_3: typeof import('./src/components/NiSkeleton/src/NiSkeletonFile4_3.vue')['default']
    NiSkeletonHeading: typeof import('./src/components/NiSkeleton/src/NiSkeletonHeading.vue')['default']
    NiSkeletonImage1_1: typeof import('./src/components/NiSkeleton/src/NiSkeletonImage1_1.vue')['default']
    NiSkeletonImage16_9: typeof import('./src/components/NiSkeleton/src/NiSkeletonImage16_9.vue')['default']
    NiSkeletonImage4_3: typeof import('./src/components/NiSkeleton/src/NiSkeletonImage4_3.vue')['default']
    NiSkeletonInput: typeof import('./src/components/NiSkeleton/src/NiSkeletonInput.vue')['default']
    NiSkeletonInputActive: typeof import('./src/components/NiSkeleton/src/NiSkeletonInputActive.vue')['default']
    NiSkeletonListClosed: typeof import('./src/components/NiSkeleton/src/NiSkeletonListClosed.vue')['default']
    NiSkeletonListOpen: typeof import('./src/components/NiSkeleton/src/NiSkeletonListOpen.vue')['default']
    NiSkeletonLoader: typeof import('./src/components/NiSkeleton/src/NiSkeletonLoader.vue')['default']
    NiSkeletonTextBody: typeof import('./src/components/NiSkeleton/src/NiSkeletonTextBody.vue')['default']
    NiSkeletonTextBody1: typeof import('./src/components/NiSkeleton/src/NiSkeletonTextBody1.vue')['default']
    NiSkeletonTextBody2: typeof import('./src/components/NiSkeleton/src/NiSkeletonTextBody2.vue')['default']
    NiSkeletonTextBody3: typeof import('./src/components/NiSkeleton/src/NiSkeletonTextBody3.vue')['default']
    NiSkeletonVideo1_1: typeof import('./src/components/NiSkeleton/src/NiSkeletonVideo1_1.vue')['default']
    NiSkeletonVideo16_9: typeof import('./src/components/NiSkeleton/src/NiSkeletonVideo16_9.vue')['default']
    NiSkeletonVideo4_3: typeof import('./src/components/NiSkeleton/src/NiSkeletonVideo4_3.vue')['default']
    NiVLayout: typeof import('./src/components/NiVLayout/src/NiVLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
