/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Example: typeof import('./src/components/NiVLayout/docs/Example.vue')['default']
    IExample: typeof import('./src/components/NiVLayout/docs/IExample.vue')['default']
    NiVLayout: typeof import('./src/components/NiVLayout/src/NiVLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
