blank_issues_enabled: false
contact_links:
  - name: 社区支持
    url: https://github.com/NI-Web-Infra-Team/ni-material-market/discussions
    about: 请在这里进行问题的讨论
  - name: 贡献指南
    url: https://github.com/NI-Web-Infra-Team/ni-material-market/blob/main/.github/CONTRIBUTING.zh-CN.md
    about: 如果您不知道如何提交一个 issue，请查看项目贡献指南
