import { withInstall } from '@/utils/install';

import Avatar from './src/NiSkeletonAvatar.vue';
import ButtonPrimary from './src/NiSkeletonButtonPrimary.vue';
import ButtonSecondary from './src/NiSkeletonButtonSecondary.vue';
import Input from './src/NiSkeletonInput.vue';
import InputActive from './src/NiSkeletonInputActive.vue';
import ListClosed from './src/NiSkeletonListClosed.vue';
import ListOpen from './src/NiSkeletonListOpen.vue';
import Loader from './src/NiSkeletonLoader.vue';
import Heading from './src/NiSkeletonHeading.vue';
import TextBody1 from './src/NiSkeletonTextBody1.vue';
import TextBody2 from './src/NiSkeletonTextBody2.vue';
import TextBody3 from './src/NiSkeletonTextBody3.vue';
import Card1 from './src/NiSkeletonCard1.vue';
import Card2 from './src/NiSkeletonCard2.vue';
import Card3 from './src/NiSkeletonCard3.vue';
import CTASection from './src/NiSkeletonCTASection.vue';
import Image1_1 from './src/NiSkeletonImage1_1.vue';
import Image4_3 from './src/NiSkeletonImage4_3.vue';
import Image16_9 from './src/NiSkeletonImage16_9.vue';
import Video1_1 from './src/NiSkeletonVideo1_1.vue';
import Video4_3 from './src/NiSkeletonVideo4_3.vue';
import Video16_9 from './src/NiSkeletonVideo16_9.vue';
import File1_1 from './src/NiSkeletonFile1_1.vue';
import File4_3 from './src/NiSkeletonFile4_3.vue';
import File16_9 from './src/NiSkeletonFile16_9.vue';

export const NiSkeletonAvatar = withInstall(Avatar);
export const NiSkeletonButtonPrimary = withInstall(ButtonPrimary);
export const NiSkeletonButtonSecondary = withInstall(ButtonSecondary);
export const NiSkeletonInput = withInstall(Input);
export const NiSkeletonInputActive = withInstall(InputActive);
export const NiSkeletonListClosed = withInstall(ListClosed);
export const NiSkeletonListOpen = withInstall(ListOpen);
export const NiSkeletonLoader = withInstall(Loader);
export const NiSkeletonHeading = withInstall(Heading);
export const NiSkeletonTextBody1 = withInstall(TextBody1);
export const NiSkeletonTextBody2 = withInstall(TextBody2);
export const NiSkeletonTextBody3 = withInstall(TextBody3);
export const NiSkeletonCard1 = withInstall(Card1);
export const NiSkeletonCard2 = withInstall(Card2);
export const NiSkeletonCard3 = withInstall(Card3);
export const NiSkeletonCTASection = withInstall(CTASection);
export const NiSkeletonImage1_1 = withInstall(Image1_1);
export const NiSkeletonImage4_3 = withInstall(Image4_3);
export const NiSkeletonImage16_9 = withInstall(Image16_9);
export const NiSkeletonVideo1_1 = withInstall(Video1_1);
export const NiSkeletonVideo4_3 = withInstall(Video4_3);
export const NiSkeletonVideo16_9 = withInstall(Video16_9);
export const NiSkeletonFile1_1 = withInstall(File1_1);
export const NiSkeletonFile4_3 = withInstall(File4_3);
export const NiSkeletonFile16_9 = withInstall(File16_9);
