name: 'PR Auto Assign And Review'
on:
  pull_request:
    types: [opened, edited, reopened, ready_for_review]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Replace npmrc
        run: cp -f .github.npmrc .npmrc

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
          echo "pnpm_cache_dir=$(pnpm store path)" >> $env:GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Add assigness
        if: ${{ !contains(github.event.pull_request.user.login ,'[bot]') }}
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-assignees'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          assignees: ${{ github.event.pull_request.user.login }}

      - name: Add reviewers
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          OWNER: ${{ github.event.pull_request.head.repo.owner.login }}
          REPO: ${{ github.event.pull_request.head.repo.name }}
          PULL_NUMBER: ${{ github.event.pull_request.number }}
          AUTHOR: ${{ github.event.pull_request.user.login }}
          COUNT: 2
        run: |
          curl https://raw.githubusercontent.com/NI-Web-Infra-Team/common-utils/development/scripts/autoAssignAndReview.cjs -o ./scripts/autoAssignAndReview.cjs
          node ./scripts/autoAssignAndReview.cjs
