# Unit Test Coverage Report

name: Test Coverage

on:
  pull_request:
    branches:
      - development

jobs:
  build:
    name: Coverage
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions-cool/check-user-permission@v2
        id: checkUser
        with:
          require: 'write'

      - uses: actions/cache@v3
        name: Setup cypress cache
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress
          restore-keys: |
            ${{ runner.os }}-cypress

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Replace npmrc
        run: cp -f .github.npmrc .npmrc

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
          echo "pnpm_cache_dir=$(pnpm store path)" >> $env:GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Generate banner
        run: pnpm run banner

      - name: Generate coverage
        run: pnpm run test-coverage

      - name: Merge unit and e2e coverage
        run: node ./scripts/mergeCoverageReport.cjs

      - name: 'Report Coverage'
        if: always() # Also generate the report if tests are failing
        uses: davelosert/vitest-coverage-report-action@v1
